/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleRelatorios;
import dao.MovimentosDao;
import dao.PessoaDao;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Movimentos;
import model.Pessoa;
import model.Util;

/**
 *
 * @author robso
 */
public class TabelaMovimentos extends javax.swing.JDialog {

    MovimentosDao mDao = new MovimentosDao();
    List<Movimentos> movimentos;
    String tipo;
    Pessoa usuario = null;

    /**
     * Creates new form TabelaPessoa
     */
    public TabelaMovimentos(java.awt.Frame parent, boolean modal, Pessoa usuario, String tipo) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        this.usuario = usuario;
        this.tipo = tipo;

//        if (tipo.equals("C")){
//            lbTitulo.setText("ENTRADAS");
//        }else {
//            lb
//        }
        lbTitulo.setText(tipo.equals("C") ? "ENTRADAS" : "SAIDAS");

        carregarTabelaMovimentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlterar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMovimentos = new javax.swing.JTable();
        lbTitulo = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btPesquisarPessoa = new javax.swing.JButton();
        jButton1 = new niceswing.JButton.JButton();
        jPanel1 = new javax.swing.JPanel();
        vfTotal = new niceswing.JValueField.JValueField();
        jTextField1 = new niceswing.JTextField.JTextField();
        jTextField2 = new niceswing.JTextField.JTextField();
        dfDataIni = new niceswing.JDateField.JDateField();
        jTextField3 = new niceswing.JTextField.JTextField();
        dfDataFin = new niceswing.JDateField.JDateField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        btnInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInserirKeyPressed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tbMovimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbMovimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMovimentosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbMovimentos);

        lbTitulo.setText(">>>");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        btPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarPessoaActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTextField1.setText("TOTAL: ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(vfTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTextField2.setText("Data Inicial");

        jTextField3.setText("Data Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dfDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dfDataFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btPesquisarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dfDataFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dfDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbMovimentos.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro");
        } else {
            int i = linhaSelecionada;
            Movimentos m = movimentos.get(i);

            FormularioMovimentos_Combo dialogo = new FormularioMovimentos_Combo(null, true, m, usuario.id, this.tipo);

            dialogo.setVisible(true);
            if (dialogo.m != null) {

                //pessoas.set(i, dialogo.p);
                mDao = new MovimentosDao();
                mDao.alterar(dialogo.m);

                carregarTabelaMovimentos();
            }
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        FormularioMovimentos dialogo = new FormularioMovimentos(null, true, usuario.id, this.tipo);

        dialogo.setVisible(true);

        if (dialogo.m != null) {
            //pessoas.add(dialogo.p);
            mDao = new MovimentosDao();
            mDao.gravar(dialogo.m);

            carregarTabelaMovimentos();
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInserirKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnInserirKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbMovimentos.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro");
        } else {
            int i = linhaSelecionada;

            Movimentos m = movimentos.get(i);

            //pessoas.remove(i);
            mDao = new MovimentosDao();
            mDao.remover(m);

            carregarTabelaMovimentos();
        }

        //        if (tfIndice.getText().equals("")) {
        //            JOptionPane.showMessageDialog(rootPane, "Informe o Indíce");
        //        } else {
        //            int i = Integer.parseInt(tfIndice.getText());
        //            pessoas.remove(i);
        //            carregarTabelaPessoa();
        //        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarPessoaActionPerformed
        // TODO add your handling code here:

        carregarTabelaMovimentos();
    }//GEN-LAST:event_btPesquisarPessoaActionPerformed

    private void tbMovimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMovimentosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 3) {
            Util.larguraColunas(tbMovimentos);
        }
    }//GEN-LAST:event_tbMovimentosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Map parametros = new HashMap();
        parametros.put("DataIni", dfDataIni.getDate());
        parametros.put("DataFin", dfDataFin.getDate());

        ControleRelatorios controle = new ControleRelatorios();
        controle.imprimirRelatorio(this, movimentos, "Entrada", parametros);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaMovimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaMovimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaMovimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaMovimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TabelaMovimentos dialog = new TabelaMovimentos(new javax.swing.JFrame(), true, null, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisarPessoa;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private niceswing.JDateField.JDateField dfDataFin;
    private niceswing.JDateField.JDateField dfDataIni;
    private niceswing.JButton.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private niceswing.JTextField.JTextField jTextField1;
    private niceswing.JTextField.JTextField jTextField2;
    private niceswing.JTextField.JTextField jTextField3;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tbMovimentos;
    private niceswing.JValueField.JValueField vfTotal;
    // End of variables declaration//GEN-END:variables

    private void carregarTabelaMovimentos() {
        String condicao = " where 1=1 "
                + " and m.id_usuario = " + this.usuario.id
                + " and m.tipo = '" + this.tipo + "'"
                + " and m.data between '" + Util.dataFormatoSql(dfDataIni.getText()) + "'"
                + " and "
                + "'" + Util.dataFormatoSql(dfDataFin.getText()) + "'"
                + " order by data ";
        mDao = new MovimentosDao();

//        String nome = tfNome.getText();
//        if (!"".equals(nome)) {
//            condicao += " and nome like '%" + nome + "%' ";
//        }

        movimentos = mDao.listar(condicao);

        String[] colunas = new String[]{
            "Data", "Pessoa", "Obs", "Valor"
        };
        this.tbMovimentos.setModel(new DefaultTableModel(colunas, 0) {
            Class[] types = new Class[]{String.class, String.class, String.class, String.class};
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        DefaultTableModel dtm = (DefaultTableModel) tbMovimentos.getModel();

        int linha = this.tbMovimentos.getRowCount();
        for (int c = 0; c < linha; c++) {
            dtm.removeRow(0);
        }

        Double total = 0.0;
        for (Movimentos m : movimentos) {
            total += m.valor;
            Object[] dado = new Object[4];
            dado[0] = m.data;
            dado[1] = m.nome_pessoa;
            dado[2] = m.obs;
            dado[3] = m.valorFormatado();

            dtm.addRow(dado);
        }
        vfTotal.setDoubleValue(total);

        tbMovimentos.getColumnModel().getColumn(0).setPreferredWidth(51);
        tbMovimentos.getColumnModel().getColumn(1).setPreferredWidth(172);
        tbMovimentos.getColumnModel().getColumn(2).setPreferredWidth(417);
        tbMovimentos.getColumnModel().getColumn(3).setPreferredWidth(62);

        tbMovimentos.getColumnModel().getColumn(3).setCellRenderer(Util.alinhaDireita());

    }
}
